version: 2
updates:
  - package-ecosystem: pip
    directory: /bridge
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    ignore:
      - dependency-name: python
        versions:
          - ">=3.13"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
